esphome:
  name: goodnature_ble_monitor
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "Your_WiFi_SSID"
  password: "Your_WiFi_Password"

# Enable Home Assistant API
api:

# Enable OTA updates
ota:

# Enable logging
logger:

# Enable Web server
web_server:
  port: 80

# Enable Bluetooth Low Energy
esp32_ble_tracker:

# Sensor configurations
sensor:
  - platform: goodnature_ble
    mac_address: "D3:58:7F:15:99:0B"
    name: "Front yard trap"
  - platform: goodnature_ble
    kill_count:
      name: "Goodnature Kill Count"
      id: goodnature_kill_count
    battery_level:
      name: "Goodnature Battery Level"
      id: goodnature_battery_level
    last_activation:
      name: "Goodnature Last Activation"
      id: goodnature_last_activation

